Repository UDT-Uplus-Dream-Team/UDT-be, pull requests merged in 2025-07, with the labels that each got.

#64 Feat/udt 84 엄선된 추천 알고리즘
  src/main/java/com/example/udtbe/domain/content/controller/RecommendContentController.java
  src/main/java/com/example/udtbe/domain/content/controller/RecommendContentControllerApiSpec.java
  src/main/java/com/example/udtbe/domain/content/service/ContentRecommendationService.java
  src/main/java/com/example/udtbe/domain/content/service/LuceneSearchService.java
  src/test/java/com/example/udtbe/common/fixture/ContentMetadataFixture.java
  src/test/java/com/example/udtbe/content/service/ContentRecommendationServiceTest.java
Labels: ✨ Feature, 🔨 Refactor, ✅ Test

#67 feat/UDT-96-OTT-콘텐츠-인기-목록-조회
  src/main/java/com/example/udtbe/domain/content/controller/ContentController.java
  src/main/java/com/example/udtbe/domain/content/controller/ContentControllerApiSpec.java
  src/main/java/com/example/udtbe/domain/content/dto/FeedbackMapper.java
  src/main/java/com/example/udtbe/domain/content/dto/request/PopularContentsRequest.java
  src/main/java/com/example/udtbe/domain/content/dto/response/PopularContentsResponse.java
  src/main/java/com/example/udtbe/domain/content/repository/FeedbackRepository.java
  src/main/java/com/example/udtbe/domain/content/service/ContentService.java
  src/main/java/com/example/udtbe/domain/content/util/InMemoryPopularContentStore.java
  src/main/java/com/example/udtbe/domain/content/util/PopularContentStore.java
  src/test/java/com/example/udtbe/content/repository/FeedbackRepositoryTest.java
Labels: ✨ Feature

#66 fix/UDT-106 마이페이지 장르, 플랫폼 정보 한국어로 반환
  src/main/java/com/example/udtbe/domain/content/entity/enums/PlatformType.java
  src/main/java/com/example/udtbe/domain/member/dto/request/MemberCuratedContentGetsRequest.java
  src/main/java/com/example/udtbe/domain/member/service/MemberService.java
  src/test/java/com/example/udtbe/content/controller/ContentControllerTest.java
  src/test/java/com/example/udtbe/member/service/MemberServiceTest.java
Labels: 🐞 BugFix

#75 fix/UDT-114-요일별-콘텐츠-목록-조회-테스트-검증-버그
  src/test/java/com/example/udtbe/content/controller/ContentControllerTest.java
Labels: wontfix, 🐞 BugFix

#77 Feat/udt 115 엄선된콘텐츠저장
  src/main/java/com/example/udtbe/domain/content/controller/RecommendContentController.java
  src/main/java/com/example/udtbe/domain/content/controller/RecommendContentControllerApiSpec.java
  src/main/java/com/example/udtbe/domain/content/dto/request/CuratedContentListDeleteRequest.java
  src/main/java/com/example/udtbe/domain/content/dto/request/CuratedContentRequest.java
  src/main/java/com/example/udtbe/domain/content/entity/CuratedContent.java
  src/main/java/com/example/udtbe/domain/content/exception/ContentErrorCode.java
  src/main/java/com/example/udtbe/domain/content/repository/CuratedContentRepository.java
  src/main/java/com/example/udtbe/domain/content/service/ContentQuery.java
  src/main/java/com/example/udtbe/domain/content/service/ContentService.java
  src/main/java/com/example/udtbe/domain/member/controller/MemberController.java
  src/main/java/com/example/udtbe/domain/member/controller/MemberControllerApiSpec.java
  src/test/java/com/example/udtbe/common/fixture/CuratedContentFixture.java
  src/test/java/com/example/udtbe/content/service/ContentServiceTest.java
Labels: ✨ Feature, ✅ Test

#93 chore/배포
  .github/workflows/cd_prod.yml
Labels: 🥹 Deploy

#95 feat/UDT-132-Redis-Config-수정
  src/main/java/com/example/udtbe/global/config/RedisConfig.java
  src/test/java/com/example/udtbe/common/config/TestRedisConfig.java
  src/test/java/com/example/udtbe/common/support/ApiSupport.java
Labels: ⚙ Setting, ✨ Feature, ✅ Test

#97 chore/배포
  src/main/java/com/example/udtbe/domain/content/entity/Director.java
  src/main/java/com/example/udtbe/domain/survey/service/SurveyService.java
  src/main/java/com/example/udtbe/global/config/RedisConfig.java
  src/test/java/com/example/udtbe/common/config/TestRedisConfig.java
  src/test/java/com/example/udtbe/common/support/ApiSupport.java
  src/test/java/com/example/udtbe/survey/service/SurveyServiceTest.java
Labels: 🥹 Deploy

#98 chore/UDT-134-Prod-CD-스크립트-오류
  .github/workflows/cd_prod.yml
Labels: ⚙ Setting, 🥹 Deploy, 🐞 BugFix

#99 chore/배포
  .github/workflows/cd_prod.yml
Labels: 🥹 Deploy

#103 chore/배포
  .github/workflows/cd_prod.yml
  .gitignore
  src/main/java/com/example/udtbe/domain/admin/service/AdminService.java
  src/main/java/com/example/udtbe/domain/auth/service/AuthService.java
  src/main/java/com/example/udtbe/domain/member/service/MemberService.java
  src/main/java/com/example/udtbe/global/exception/GlobalExceptionHandler.java
  src/main/java/com/example/udtbe/global/log/ApiTraceAspect.java
  src/main/java/com/example/udtbe/global/log/MDCMemberTrace.java
  src/main/java/com/example/udtbe/global/log/MDCRequestTrace.java
  src/main/java/com/example/udtbe/global/log/annotation/LogReturn.java
  src/main/java/com/example/udtbe/global/token/cookie/ProdCookie.java
  src/main/java/com/example/udtbe/global/token/service/TokenProvider.java
Labels: 🥹 Deploy

#105 chore/UDT-144-CD-XMl-생성-스크립트-변경
  .github/workflows/cd_prod.yml
Labels: 🐞 BugFix

#108 chore/배포
  .github/workflows/cd_prod.yml
  .gitignore
  build.gradle
  src/main/resources/logback-spring.xml
Labels: 🥹 Deploy

#104 chore/운영서버 배포
  .gitignore
  build.gradle
  src/main/java/com/example/udtbe/domain/admin/service/AdminService.java
  src/main/java/com/example/udtbe/domain/auth/service/AuthService.java
  src/main/java/com/example/udtbe/domain/member/service/MemberService.java
  src/main/java/com/example/udtbe/global/exception/GlobalExceptionHandler.java
  src/main/java/com/example/udtbe/global/log/ApiTraceAspect.java
  src/main/java/com/example/udtbe/global/log/MDCMemberTrace.java
  src/main/java/com/example/udtbe/global/log/MDCRequestTrace.java
  src/main/java/com/example/udtbe/global/log/annotation/LogReturn.java
  src/main/java/com/example/udtbe/global/token/cookie/ProdCookie.java
  src/main/java/com/example/udtbe/global/token/service/TokenProvider.java
  src/main/resources/logback-spring.xml
Labels: 🥹 Deploy

#101 Feat/udt 139 추천 알고리즘 메모리 적용
  src/main/java/com/example/udtbe/domain/content/entity/ContentMetadata.java
  src/main/java/com/example/udtbe/domain/content/event/IndexRebuildCompleteEvent.java
  src/main/java/com/example/udtbe/domain/content/service/ContentRecommendationService.java
  src/main/java/com/example/udtbe/domain/content/service/LuceneIndexService.java
  src/main/java/com/example/udtbe/domain/content/service/LuceneSearchService.java
  src/main/java/com/example/udtbe/domain/content/util/MemberRecommendationCache.java
  src/main/java/com/example/udtbe/domain/content/util/RecommendationCacheManager.java
  src/test/java/com/example/udtbe/content/service/ContentRecommendationServiceTest.java
Labels: ✨ Feature

#113 feat/UDT-149-health-check-jwt-filter-Skip-URI-추가
  src/main/java/com/example/udtbe/global/config/SecurityConfig.java
  src/main/java/com/example/udtbe/global/token/filter/TokenAuthenticationFilter.java
Labels: ✨ Feature

#115 chore/배포
  src/main/java/com/example/udtbe/domain/content/entity/Content.java
  src/main/java/com/example/udtbe/domain/survey/service/SurveyService.java
  src/main/java/com/example/udtbe/global/config/SecurityConfig.java
  src/main/java/com/example/udtbe/global/log/MDCMemberTrace.java
  src/main/java/com/example/udtbe/global/token/filter/TokenAuthenticationFilter.java
  src/main/java/com/example/udtbe/global/token/filter/TokenExceptionFilter.java
Labels: 🥹 Deploy

#116 refator/UDT-152-기존-Error-Log-레벨-다운-및-각종-로그-관련-변경
  src/main/java/com/example/udtbe/domain/content/service/ContentQuery.java
  src/main/java/com/example/udtbe/global/log/ApiTraceAspect.java
  src/main/java/com/example/udtbe/global/log/MDCMemberTrace.java
  src/main/java/com/example/udtbe/global/security/handler/CustomAccessDeniedHandler.java
  src/main/java/com/example/udtbe/global/security/handler/CustomAuthenticationEntryPoint.java
  src/main/java/com/example/udtbe/global/security/handler/CustomOauth2FailureHandler.java
  src/main/java/com/example/udtbe/global/token/filter/TokenExceptionFilter.java
  src/main/resources/logback-spring.xml
Labels: ⚙ Setting, ✨ Feature, 🔨 Refactor

#118 chore/배포
  src/main/java/com/example/udtbe/domain/content/service/ContentQuery.java
  src/main/java/com/example/udtbe/global/config/SecurityConfig.java
  src/main/java/com/example/udtbe/global/log/ApiTraceAspect.java
  src/main/java/com/example/udtbe/global/log/MDCMemberTrace.java
  src/main/java/com/example/udtbe/global/security/exception/SecurityErrorCode.java
  src/main/java/com/example/udtbe/global/security/handler/CustomAccessDeniedHandler.java
  src/main/java/com/example/udtbe/global/security/handler/CustomAuthenticationEntryPoint.java
  src/main/java/com/example/udtbe/global/security/handler/CustomOauth2FailureHandler.java
  src/main/java/com/example/udtbe/global/token/filter/TokenExceptionFilter.java
  src/main/resources/logback-spring.xml
  src/test/java/com/example/udtbe/admin/controller/AdminControllerTest.java
  src/test/java/com/example/udtbe/member/controller/MemberControllerTest.java
Labels: 🥹 Deploy

#123 chore/UDT-155 fix: 프로메테우스 인증 문제 해결
  src/main/java/com/example/udtbe/global/config/SecurityConfig.java
  src/main/java/com/example/udtbe/global/token/filter/TokenAuthenticationFilter.java
Labels: ⚙ Setting

#129 fix/UDT-157-token-filter-blacklist-verify-bug
  src/main/java/com/example/udtbe/domain/auth/service/AuthService.java
  src/main/java/com/example/udtbe/global/token/filter/TokenAuthenticationFilter.java
  src/main/java/com/example/udtbe/global/token/service/TokenProvider.java
  src/test/java/com/example/udtbe/auth/service/AuthServiceTest.java
Labels: 🐞 BugFix, 🔨 Refactor

#132 chore/배포
  src/main/java/com/example/udtbe/domain/auth/service/AuthService.java
  src/main/java/com/example/udtbe/global/token/cookie/ProdCookie.java
  src/main/java/com/example/udtbe/global/token/filter/TokenAuthenticationFilter.java
  src/main/java/com/example/udtbe/global/token/service/TokenProvider.java
  src/test/java/com/example/udtbe/auth/service/AuthServiceTest.java
Labels: 🥹 Deploy

#133 chore/배포
  src/main/java/com/example/udtbe/domain/auth/service/AuthService.java
  src/main/java/com/example/udtbe/global/token/cookie/ProdCookie.java
  src/main/java/com/example/udtbe/global/token/filter/TokenAuthenticationFilter.java
  src/main/java/com/example/udtbe/global/token/service/TokenProvider.java
  src/test/java/com/example/udtbe/auth/service/AuthServiceTest.java
Labels: 🥹 Deploy

#142 refactor/UDT-170-온보딩-신규-유저-헤더-변경
  src/main/java/com/example/udtbe/domain/survey/service/SurveyService.java
  src/main/java/com/example/udtbe/global/token/cookie/CookieConfig.java
  src/main/java/com/example/udtbe/global/token/cookie/CookieUtil.java
  src/main/java/com/example/udtbe/global/token/cookie/DevCookie.java
  src/main/java/com/example/udtbe/global/token/cookie/LocalCookie.java
  src/main/java/com/example/udtbe/global/token/cookie/ProdCookie.java
  src/test/java/com/example/udtbe/survey/controller/SurveyControllerTest.java
  src/test/java/com/example/udtbe/survey/service/SurveyServiceTest.java
Labels: ✨ Feature, 🐞 BugFix, 🔨 Refactor

#143 chore/배포
  src/main/java/com/example/udtbe/domain/survey/service/SurveyService.java
  src/main/java/com/example/udtbe/global/token/cookie/CookieConfig.java
  src/main/java/com/example/udtbe/global/token/cookie/CookieUtil.java
  src/main/java/com/example/udtbe/global/token/cookie/DevCookie.java
  src/main/java/com/example/udtbe/global/token/cookie/LocalCookie.java
  src/main/java/com/example/udtbe/global/token/cookie/ProdCookie.java
  src/test/java/com/example/udtbe/survey/controller/SurveyControllerTest.java
  src/test/java/com/example/udtbe/survey/service/SurveyServiceTest.java
Labels: 🥹 Deploy

#144 chore/배포
  src/main/java/com/example/udtbe/domain/survey/service/SurveyService.java
  src/main/java/com/example/udtbe/global/token/cookie/CookieConfig.java
  src/main/java/com/example/udtbe/global/token/cookie/CookieUtil.java
  src/main/java/com/example/udtbe/global/token/cookie/DevCookie.java
  src/main/java/com/example/udtbe/global/token/cookie/LocalCookie.java
  src/main/java/com/example/udtbe/global/token/cookie/ProdCookie.java
  src/test/java/com/example/udtbe/survey/controller/SurveyControllerTest.java
  src/test/java/com/example/udtbe/survey/service/SurveyServiceTest.java
Labels: 🥹 Deploy

#147 fix/UDT-188-JWT-재발급-401-403-버그-픽스
  src/main/java/com/example/udtbe/global/config/SecurityConfig.java
  src/main/java/com/example/udtbe/global/token/filter/TokenAuthenticationFilter.java
Labels: 🐞 BugFix

#145 refactor/UDT-135-feedback-다중-삭제로-변경
  src/main/java/com/example/udtbe/domain/content/controller/FeedbackController.java
  src/main/java/com/example/udtbe/domain/content/controller/FeedbackControllerApiSpec.java
  src/main/java/com/example/udtbe/domain/content/dto/request/FeedbackListDeleteRequest.java
  src/main/java/com/example/udtbe/domain/content/repository/FeedbackRepository.java
  src/main/java/com/example/udtbe/domain/content/service/FeedbackQuery.java
  src/main/java/com/example/udtbe/domain/content/service/FeedbackService.java
  src/main/java/com/example/udtbe/domain/member/controller/MemberController.java
  src/test/java/com/example/udtbe/content/service/FeedbackServiceTest.java
  temp.md
Labels: 🔨 Refactor
